name: Rastreador de Empleo Publico Pliega

on:
  schedule:
    # 8:00 AM y 15:00 PM (Boletines masivos BOE/PAG)
    - cron: '0 6,13 * * 1-5'
    # 9:00 AM y 16:00 PM (Llamamientos continuos autonómicos GVA/CCAA)
    - cron: '0 7,14 * * 1-5'
  workflow_dispatch: # Permite pulsar el botón manual siempre que quieras

jobs:
  scrapedata:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install @supabase/supabase-js

      - name: Ejecutar Rastreador de Convocatorias
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node crawler.js
